image: python:3-alpine

stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build:
  script:
    - apk update && apk add make
    - pip install -r requirements.txt
    - make publish

test:
  extends: .build
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pages:
  extends: .build
  stage: deploy
  artifacts:
    paths:
      - output/
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
