image: python:3-alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build:
  script:
    - apk update && apk add make
    - pip install -r requirements.txt
    - sed -i "s#^SITEURL.*#SITEURL = '/${CI_PROJECT_NAME}'#g" pelicanconf.py publishconf.py
    - make publish
    - cp content/extra/* public/

test:
  extends: .build
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pages:
  extends: .build
  stage: deploy
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
